live_config_reload = true

import = [
  #"~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
  "~/.config/alacritty/themes/themes/nightfly.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

[window.dimensions]
columns = 120
lines = 44

[window.padding]
x = 10
y = 5

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font Mono Med"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"


[scrolling]
history = 2000

# Selection settings
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

