require('settings')
require('plugins/packer')
--require('plugins/nvim-tree')
require('plugins/indent-blankline')
require('colors')
require('plugins/feline')
require('plugins/vista')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require('plugins/nvim-treesitter')
--require('plugins/alpha-nvim')

